### PR TITLE
target/riscv: fix memory access result type checker function return in case of assertion

### PR DESCRIPTION
**Pull request by fkhaidari**

### CODE REVIEW

**Comment by TommyMurphyTM1234** [comment]
Wow! I assumed that "XXXX" was a placeholder for a particular expletive starting with 'F'. 😄

**Comment by fkhaidari** [comment]
> Wow! I assumed that "XXXX" was a placeholder for a particular expletive starting with 'F'. 😄

Oh... Maybe I should rename it to avoid ambiguity 😅

**Review by aap-sc — APPROVED** [review]

**Comment by aap-sc** [comment]
LGTM (reviewed internally).

@JanMatCodasip would you kindly take a look?

**Review by JanMatCodasip — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
