### PR TITLE
[NFC] target/riscv: refactor `init_registers()`

### PR DESCRIPTION
**Pull request by en-sc**
The logic in `init_registers()` was quite convoluted. Initialization of each `struct reg` field is separated into function `gdb_regno_<field_name>()`.
IMHO, this makes it much easier to reason about the code.

Change-Id: Id7faa1464ce026cc5025585d0a6a95a01fb39cee

### CODE REVIEW

**Comment by en-sc** [comment]
Changed the PR to incorporate 33573cda4aa5685b32c44a81b1f2d84a28d78810

**Review by MarekVCodasip — DISMISSED** [review]
Looks good, thank you, this improves the readability a lot.

Quickly discussed with @JanMatCodasip too, who is in favor as well.

**Comment by en-sc** [comment]
@MarekVCodasip, there was a merge conflict with 33573cda4aa5685b32c44a81b1f2d84a28d78810, please, take a look. The resolution was to use the version from this commit, as planned (see [a previous comment on the matter](https://github.com/riscv-collab/riscv-openocd/pull/1022#issuecomment-1983132591)).

**Review by MarekVCodasip — APPROVED** [review]
Took a look, LGTM

**Pull request merged**
