### PR TITLE
Create `riscv repeat_read` command

### PR DESCRIPTION
**Pull request by timsifive**
SiFive uses to quickly read out an on-chip trace buffer, but there are probably other uses for this functionality. They probably all involve reading out a buffer that is memory-mapped at a single address.

Currently not supported using abstract commands. The bulk of the change is to rewrite `read_memory_progbuf_inner` to use a counter to track progress, instead of the address.

### CODE REVIEW

**Review by GregSavin — COMMENTED** [review]
So, previously, it was implicit that increment==size?   And now increment is explicit, and it can be supplied as zero in some cases (SBA?)?   Or you can supply increment of zero for any progbuf-based memory read?

**Comment by GregSavin** [comment]
OK, never mind, I see now.

**Review by GregSavin — DISMISSED** [review]
Always fascinating to see the ripple effects that needed to be dealt with (e.g. the omission of address field in "md" output).  Looks good to me, though.

**Comment by timsifive** [comment]
Thanks, @SiFiveGregS. Can you rereview? I had to resolve a conflict.

**Review by GregSavin — APPROVED** [review]

**Pull request merged**
