### PR TITLE
Update libjaylink

### PR DESCRIPTION
**Pull request by zqb-all**
Change-Id: Ia8f90926dd96fa0f122eb5e6d61f7c9c5263fa6e

### CODE REVIEW

**Comment by timsifive** [comment]
What's the rationale for this?

**Comment by zqb-all** [comment]
> What's the rationale for this?

Libjaylink not support my jlink, then I send a patch to libjaylink to support it and now the patch is merged

https://gitlab.zapb.de/libjaylink/libjaylink/-/commit/3f356226f996ea60f685a27914b829c77e5a8aef

Update libjaylink can help others with the same problem

**Comment by TommyMurphyTM1234** [comment]
In case it's of any relevance here - or in the future - note that upstream OpenOCD have recently started deprecating the building of libjaylink as a submodule and moving to it being obtained separately. See here:

* https://github.com/openocd-org/openocd/commit/8bb926eb01022998ceefe666f8df102e59404015

For the latest upstream OpenOCD if you want to build OpenOCD with the submodule libjaylink then you have to specify `--enable-internal-libjaylink` at configuration time.

**Comment by zqb-all** [comment]
Should I send this patch to upstream first and then sync it from upstream after upstream merge it?

**Comment by zqb-all** [comment]
> In case it's of any relevance here - or in the future - note that upstream OpenOCD have recently started deprecating the building of libjaylink as a submodule and moving to it being obtained separately. See here:
> 
> * [openocd-org/openocd@8bb926e](https://github.com/openocd-org/openocd/commit/8bb926eb01022998ceefe666f8df102e59404015)
> 

Thank you for your information. Do you think it's necessary to keep libjaylink up to date until the --enable-internal-libjaylink config option completely removed? If no, I'll close this PR

**Comment by TommyMurphyTM1234** [comment]
> Should I send this patch to upstream first and then sync it from upstream after upstream merge it?

>  Do you think it's necessary to keep libjaylink up to date until the --enable-internal-libjaylink config option completely removed? If no, I'll close this PR

Sorry - I don't really know the answer to these questions.
Perhaps it would be worth asking on the OpenOCD-devel list?

* https://sourceforge.net/p/openocd/mailman/openocd-devel/

**Comment by zqb-all** [comment]
> Perhaps it would be worth asking on the OpenOCD-devel list?
> 
> * https://sourceforge.net/p/openocd/mailman/openocd-devel/

OK，Thanks

**Comment by zqb-all** [comment]
As libjaylink is in the process of being removed from openocd, don't need to update it now

**Pull request closed without merging**
