### PR TITLE
From upstream

### PR DESCRIPTION
**Pull request by timsifive**
Do this again, to establish a clean merge-base. The previous merge from upstream happened while other changes were going into `riscv`, which I suspect muddled the history.

### CODE REVIEW

**Comment by ilg-ul** [comment]
The semihosting patch was finally approved by Matthias, I hope it'll be merged soon, so please plan for a new merge from upstream once this is done.

**Comment by timsifive** [comment]
I'll do another upstream merge once your changes are in.

**Review by palmer-dabbelt — APPROVED** [review]

**Comment by ilg-ul** [comment]
> I'll do another upstream merge once your changes are in.

My changes are in now.

**Comment by timsifive** [comment]
I'll pull from upstream again next week.

**Pull request merged**
