### PR TITLE
riscv: Avoid shadowing read_csr/write_csr macros

### PR DESCRIPTION
**Pull request by kraj**
The name conflict is picked by compiler and it fails to compile for rv64
Fixes
src/target/riscv/riscv-011.c:1014:44: error: too many arguments provided to function-like macro invocation
static int read_csr(struct target *target, uint64_t *value, uint32_t csr)
                                           ^
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by TommyMurphyTM1234** [comment]
Just curious (and not questioning the issue raised) you're compiling openocd to run on rv64 to debug what target?

**Comment by kraj** [comment]
I am just cross compiling openocd on x86 targeting rv64

**Comment by TommyMurphyTM1234** [comment]
I understand, but why do you want to run openocd *on* RISC-V?
What sort of target will you be debugging when running openocd on a RISC-V host?

**Comment by kraj** [comment]
> I understand, but why do you want to run openocd _on_ RISC-V?
> What sort of target will you be debugging when running openocd on a RISC-V host?

No I don't tend to use it on RV64 host yet but that should not be a consideration for this patch
the code is wrong and it should be fixed regardless

**Comment by TommyMurphyTM1234** [comment]
Ok, fair enough.
I was just curious about how you intended to run openocd on RISC-V.
Thanks.

**Review by timsifive — CHANGES_REQUESTED** [review]
This looks like a decent solution to the problem, but can you use read_remote_csr and write_remote_csr instead of the names you chose?

**Comment by kraj** [comment]
> This looks like a decent solution to the problem, but can you use read_remote_csr and write_remote_csr instead of the names you chose?

done

**Review by timsifive — APPROVED** [review]
Thank you! I'll merge this tomorrow, unless somebody objects.

**Pull request merged**
