### PR TITLE
Add config files for SiFive RISC-V hardware.

### PR DESCRIPTION
**Pull request by timsifive**
Copied from https://github.com/gnu-mcu-eclipse/openocd

Change-Id: Ia0b3e192ca8b3bae6035623d605c9980e9bccd2c

### CODE REVIEW

**Review by palmer-dabbelt — APPROVED** [review]

**Comment by ilg-ul** [comment]
you are using older files. 

the recent version of GNU MCU Eclipse OpenOCD use the now 'official' board names:

- sifive-hifive1.cfg
- sifive-e31arty.cfg
- sifive-e51arty.cfg

(https://github.com/gnu-mcu-eclipse/openocd/tree/gnu-mcu-eclipse-dev/tcl/board)

it would be good to use the same files.

also the usage for the arty files is slightly different; since the Arty board does not have an on-board JTAG, and requires an external one, including the Olimex ARM-USB-TINY-H in the board definition is not the best way.

the ARM-USB-TINY-H is already defined in OpenOCD as 'interface/ftdi/olimex-arm-usb-tiny-h.cfg', so the metadata associated with the Arty board defines the OpenOCD configuration as:

https://github.com/micro-os-plus/sifive-arty-boards-xpack/blob/36399e3ea63af9d28b46d0d01f594e31a3f0c479/boards-xcdl.json#L78

**Comment by timsifive** [comment]
Can you submit a pull request to fix this? I just copied some files that Drew pointed me to.

**Comment by ilg-ul** [comment]
#168

**Comment by timsifive** [comment]
Thanks. With that merged, should I delete the 3 files added by this PR?

**Comment by ilg-ul** [comment]
> should I delete the 3 files added by this PR?

In my opinion, yes.

**Pull request merged**
