### PR TITLE
Add utility to combine runs of lines in log files.

### PR DESCRIPTION
**Pull request by timsifive**
Hopefully satisfies #193.

Change-Id: I427d763aeca2322b05ed88b42fd4a5f0446a654b

### CODE REVIEW

**Comment by mwachs5** [comment]
Can you show the example output?

**Comment by timsifive** [comment]
```
Info : 1952 1512 server.c:311 add_service(): Listening on port 6666 for tcl connections
Info : 1953 1512 server.c:311 add_service(): Listening on port 4444 for telnet connections
Debug: 1954 1513 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_init
Debug: 1955 1513 command.c:143 script_debug(): command - init ocd_init
## The following 32 lines repeat 124 times:
# Debug: - - riscv.c:1102 riscv_openocd_poll(): polling all harts
# Debug: - - riscv.c:1935 riscv_set_current_hartid(): setting hartid to 0, was 0
# Debug: - - riscv.c:1081 riscv_poll_hart(): polling hart 0, target->state=2
# Debug: - - riscv-013.c:379 scan(): 41b r 00000000 @11 -> + 00000000 @00
# Debug: - - riscv-013.c:379 scan(): 41b - 00000000 @11 -> + 00030382 @11
# Debug: - - riscv-013.c:390 scan():  ->  allresumeack anyresumeack allhalted anyhalted authenticated version=2
# Debug: - - riscv.c:1102 riscv_openocd_poll(): polling all harts
# Debug: - - riscv.c:1935 riscv_set_current_hartid(): setting hartid to 0, was 0
# Debug: - - riscv-013.c:379 scan(): 41b r 00000000 @10 -> + 00000000 @00
# Debug: - - riscv-013.c:379 scan(): 41b - 00000000 @10 -> + 00010001 @10
# Debug: - - riscv-013.c:390 scan():  ->  hartsello=1 dmactive
# Debug: - - riscv-013.c:379 scan(): 41b w 00000001 @10 -> + 00000000 @00
# Debug: - - riscv-013.c:390 scan():  dmactive -> 
# Debug: - - riscv-013.c:379 scan(): 41b - 00000000 @10 -> + 00010001 @10
# Debug: - - riscv-013.c:390 scan():  ->  hartsello=1 dmactive
# Debug: - - riscv.c:1081 riscv_poll_hart(): polling hart 0, target->state=2
# Debug: - - riscv-013.c:379 scan(): 41b r 00000000 @11 -> + 00000000 @00
# Debug: - - riscv-013.c:379 scan(): 41b - 00000000 @11 -> + 00030382 @11
# Debug: - - riscv-013.c:390 scan():  ->  allresumeack anyresumeack allhalted anyhalted authenticated version=2
# Debug: - - riscv.c:1102 riscv_openocd_poll(): polling all harts
# Debug: - - riscv.c:1935 riscv_set_current_hartid(): setting hartid to 1, was 1
# Debug: - - riscv-013.c:379 scan(): 41b r 00000000 @10 -> + 00000000 @00
# Debug: - - riscv-013.c:379 scan(): 41b - 00000000 @10 -> + 00000001 @10
# Debug: - - riscv-013.c:390 scan():  ->  dmactive
# Debug: - - riscv-013.c:379 scan(): 41b w 00010001 @10 -> + 00000000 @00
# Debug: - - riscv-013.c:390 scan():  hartsello=1 dmactive -> 
# Debug: - - riscv-013.c:379 scan(): 41b - 00000000 @10 -> + 00000001 @10
# Debug: - - riscv-013.c:390 scan():  ->  dmactive
# Debug: - - riscv.c:1081 riscv_poll_hart(): polling hart 1, target->state=2
# Debug: - - riscv-013.c:379 scan(): 41b r 00000000 @11 -> + 00000000 @00
# Debug: - - riscv-013.c:379 scan(): 41b - 00000000 @11 -> + 00030382 @11
# Debug: - - riscv-013.c:390 scan():  ->  allresumeack anyresumeack allhalted anyhalted authenticated version=2
Info : 5925 16275 server.c:100 add_connection(): accepting 'gdb' connection on tcp/3333
Debug: 5926 16276 breakpoints.c:354 breakpoint_clear_target_internal(): Delete all breakpoints for target: pmu.0.cpu
```

**Comment by GregSavin** [comment]
Was this utility written from scratch, or does it inherit significantly from some other code?  (Just curious because if it's all new code then I'll be even more careful when reviewing it).

**Comment by timsifive** [comment]
It's all new code, and I might still remember how it works. :-)

**Review by GregSavin — APPROVED** [review]
I wasn't familiar with enumerate() builtin... gonna remember that one.

**Pull request merged**
