### PR TITLE
Fix overflow issue in write_memory_progbuf

### PR DESCRIPTION
**Pull request by en-sc**
If range's upper bound was equal to 2^64 or the range was wrapping around 0
(which is perfectly legal), writes were not performed due to riscv_addr_t
overflow.

### CODE REVIEW

**Comment by timsifive** [comment]
This looks right. What testing have you done? Are you able to run the tests in https://github.com/riscv-software-src/riscv-tests/tree/master/debug against spike to check for regressions?

**Comment by en-sc** [comment]
I've tested my changes on spike. Though as it is - spike requires some fixes too (I'll link the PR to risc-isa-sim) soon. Once all the changes are done I can provide a regression test for that configuration.

**Comment by en-sc** [comment]
I've ran tests in riscv-tests/debug with and without proposed patches (both to spike and to riscv-openocd),  running default target (not all-tests). Regardless of configuration I've gotten two exceptions on DisconnectTest and CustomRegisterTest. Is it an issue with my environment (like gcc version), or is it an expected behavior?

**Comment by timsifive** [comment]
DisconnectTest and CustomRegisterTest pass for me, so the problem is somehow related to your setup. It could be a gdb version thing, maybe. In either case, if there are no regressions anywhere and the various memory tests pass, then I think that's enough coverage for this change. Please do rerun that with `all-tests` however, which catches more corner cases.

**Comment by en-sc** [comment]
I've changed gdb to 12.1 and ran `all-tests`. There were no exceptions (make's output is attached, can provide specific logs, if needed)
[make-all-tests.log](https://github.com/riscv/riscv-openocd/files/9217316/make-all-tests.log)

**Review by timsifive — APPROVED** [review]
Great! Thank you for running all the tests.

**Comment by en-sc** [comment]
Could you merge the PR or is there something else I need to do first?

**Comment by timsifive** [comment]
Yup. Usually I wait a day or weekend in case anyone else wants to comment.

**Pull request merged**
