### PR TITLE
Bump GitHub actions to latest versions

### PR DESCRIPTION
**Pull request by TommyMurphyTM1234**
Bump GitHub actions to latest versions to address this:

* https://github.com/riscv-collab/riscv-openocd/issues/1048

If there are any issues with any of this please let me know.
Thanks.

### CODE REVIEW

**Review by JanMatCodasip — APPROVED** [review]

**Review by MarekVCodasip — APPROVED** [review]

**Review by en-sc — APPROVED** [review]

**Comment by TommyMurphyTM1234** [comment]
Can this be merged or do I need to do anything further on it? Thanks.

**Comment by TommyMurphyTM1234** [comment]
Thanks @en-sc. 👍

**Comment by en-sc** [comment]
> Can this be merged or do I need to do anything further on it?

I would like to explain the delay: in general, approved commits are merged after a cool-off period of one or two days to give an opportunity for the community to give feedback / request changes.

I don't think this particular change strictly required following the guideline, but guidelines are to be followed...

**Comment by TommyMurphyTM1234** [comment]
Thanks @en-sc - I wasn't aware of those review guidelines so thanks for clarifying them. 👍

**Comment by sobuch** [comment]
Hi @TommyMurphyTM1234, do you think you could send the fixes from here for `.github/workflows/snapshot.yml` upstream?

I was looking to to fix the snapshot action (https://github.com/riscv-collab/riscv-openocd/compare/riscv...sobuch:riscv-openocd:fix_github_snapshot), and thought it could be better to send that there, but they miss these fixes from you as well.

**Comment by TommyMurphyTM1234** [comment]
> Hi @TommyMurphyTM1234, do you think you could send the fixes from here for `.github/workflows/snapshot.yml` upstream?
> 
> I was looking to to fix the snapshot action ([riscv...sobuch:riscv-openocd:fix_github_snapshot](https://github.com/riscv-collab/riscv-openocd/compare/riscv...sobuch:riscv-openocd:fix_github_snapshot)), and thought it could be better to send that there, but they miss these fixes from you as well.

I'm not sure that I'm the right person to be asking but, in any case, I'm not really clear on what you're requesting here. If you have changes to contribute to this repo then you need to follow the usual PR process: 

1. Fork this repo
2. In your fork create a branch (optional but recommended)
3. In your forked repo/branch make your changes 
4. Add, commit and push them to your forked repo branch
5. Create a Pull Request from your forked repo to this repo
6. It will then get reviewed and hopefully merged as usual

**Comment by sobuch** [comment]
> > Hi @TommyMurphyTM1234, do you think you could send the fixes from here for `.github/workflows/snapshot.yml` upstream?
> > I was looking to to fix the snapshot action ([riscv...sobuch:riscv-openocd:fix_github_snapshot](https://github.com/riscv-collab/riscv-openocd/compare/riscv...sobuch:riscv-openocd:fix_github_snapshot)), and thought it could be better to send that there, but they miss these fixes from you as well.
> 
> I'm not sure that I'm the right person to be asking but, in any case, I'm not really clear on what you're requesting here. If you have changes to contribute to this repo then you need to follow the usual PR process:
> 
>     1. Fork this repo
> 
>     2. In your fork create a branch (optional but recommended)
> 
>     3. In your forked repo/branch make your changes
> 
>     4. Add, commit and push them to your forked repo branch
> 
>     5. Create a Pull Request from your forked repo to this repo
> 
>     6. It will then get reviewed and hopefully merged as usual

Yes, I understand that. I meant that `snapshot.yml` is also missing your fixes from this PR in the upstream, see https://github.com/openocd-org/openocd/blob/master/.github/workflows/snapshot.yml

**Comment by TommyMurphyTM1234** [comment]
> Yes, I understand that. I meant that `snapshot.yml` is also missing your fixes from this PR in the upstream, see https://github.com/openocd-org/openocd/blob/master/.github/workflows/snapshot.yml

Sorry, I still don't understand what you mean. Please explain more clearly and in precise detail if possible/necessary. 

What specific changes do you think that this file needs right now? 

- https://github.com/riscv-collab/riscv-openocd/blob/riscv/.github/workflows/snapshot.yml

And what's the problem with creating a PR as outlined above to apply these changes?

**Comment by sobuch** [comment]
Right, sorry, let my try to explain better :smiley: 

> What specific changes do you think that this file needs right now?
> 
>     * https://github.com/riscv-collab/riscv-openocd/blob/riscv/.github/workflows/snapshot.yml 

These github snapshot actions run only after push, so it was missed when the deprecated JimTCL was handled for other actions in https://github.com/riscv-collab/riscv-openocd/pull/1215 (see e.g. fail on the latest commit https://github.com/riscv-collab/riscv-openocd/actions/runs/13072454564/job/36476904853).

I prepared a fix for that -  https://github.com/riscv-collab/riscv-openocd/compare/riscv...sobuch:riscv-openocd:fix_github_snapshot

> And what's the problem with creating a PR as outlined above to apply these changes?

I planned to do that originally, but I noticed this `snapshot.yml` file comes from upstream (https://github.com/riscv-collab/riscv-openocd/blob/riscv/.github/workflows/snapshot.yml).

And as your fixes from this PR are missing in the upstream, I wanted to ask you first, whether you want to send a patch there as well. Or maybe if there is a reason not to fix the github actions in the upstream, but only in this repo?

**Comment by TommyMurphyTM1234** [comment]
What do you mean by "upstream"?
Do you mean the main OpenOCD project? 
As far as I know they don't use GitHub actions for CI builds. 

- https://openocd.org/pages/repos.html

> All OpenOCD patches are sent to our [Gerrit](https://review.openocd.org/) server. Also hosted there is our [Jenkins CI](https://build.openocd.org/) server that tests all patches submitted to Gerrit.
> 
> See the [Developer Guide](http://openocd.org/doc/doxygen/index.html) for more info.

You should probably ask in the upstream OpenOCD mailing lists if changes to `snapshot.yml` are expected/needed there?

**Comment by sobuch** [comment]
> What do you mean by "upstream"? Do you mean the main OpenOCD project? As far as I know they don't use GitHub actions for CI builds.

Yes, well they use them on the official github mirror.

Ok, thank you. I will send it to Gerrit first, then it can be synced here if accepted.

**Pull request merged**
