### PR TITLE
Merge master to riscv

### PR DESCRIPTION
**Pull request by aka-sps**
Restore master branch history

### CODE REVIEW

**Comment by timsifive** [comment]
Is this just a change that will convince git that the merge happened, without actually changing any files (since I already brought the changes over without telling git they were merge changes)?

**Comment by aka-sps** [comment]
Yes

**Review by timsifive — APPROVED** [review]
Thank you for doing this!

**Comment by aka-sps** [comment]
Do not mention it. I did this, rather, for myself. Thanks you!

**Pull request merged**
