### PR TITLE
Perform these actions on pull requests, too.

### PR DESCRIPTION
**Pull request by timsifive**
Otherwise they don't happen if somebody makes a PR from a different
fork.

Change-Id: Ic09eb8a556e2dfbc0900e3df9f07cf7aff3d5309
Signed-off-by: Tim Newsome <tim@sifive.com>

### CODE REVIEW

**Comment by timsifive** [comment]
Now they happen twice. What?

**Comment by timsifive** [comment]
OK, this looks better.

**Review by GregSavin — COMMENTED** [review]
Any recommendations on where to read a 10000 foot level introduction to github actions?

**Comment by timsifive** [comment]
When I try to figure out I usually google "github action <foo>". The documentation at https://docs.github.com/en/actions seems pretty complete, but doesn't really have a 10k foot view.

**Review by GregSavin — APPROVED** [review]

**Pull request merged**
