### PR TITLE
Enable the RISC-V semihosting control command

### PR DESCRIPTION
**Pull request by lidie626**
After modification, the following commands will take effect: monitor riscv semihosting enable/disable
monitor riscv semihosting_fileio enable/disable

### CODE REVIEW

**Comment by TommyMurphyTM1234** [comment]
I take it that the rationale for this change is to allow `riscv` to be used as an alternative to `arm` when invoking the relevant semihosting commands? 

I'm not sure that the documenation changes are correct as they seem to add `riscv semihosting` headings/sections with no associated text?

**Comment by lidie626** [comment]
> I take it that the rationale for this change is to allow `riscv` to be used as an alternative to `arm` when invoking the relevant semihosting commands?
> 
> I'm not sure that the documenation changes are correct as they seem to add `riscv semihosting` headings/sections with no associated text?

RISC-V already has support for semihosting, including the semihosting library. I think the architecture-related field of the relevant commands could possibly include 'riscv'.

**Comment by timsifive** [comment]
The command is under `arm semihosting` because it implements a protocol that is basically the same as ARM semihosting. What problem are you trying to solve?

**Comment by lidie626** [comment]
> The command is under `arm semihosting` because it implements a protocol that is basically the same as ARM semihosting. What problem are you trying to solve?
Thanks for your reply. Considering that RISC-V does not have its own semihosting protocol, this patch is not needed for now.

**Comment by JanMatCodasip** [comment]
> Thanks for your reply. Considering that RISC-V does not have its own semihosting protocol, this patch is not needed for now.

@lidie626 - Can this merge request be closed, then?

Thank you.

**Pull request closed without merging**
