### PR TITLE
Add clang build

### PR DESCRIPTION
**Pull request by timsifive**

### CODE REVIEW

**Comment by timsifive** [comment]
Travis is very slow starting OSX builds, but this change adds clang builds on Linux which hopefully get us the same coverage.

**Comment by timsifive** [comment]
This should fix #103.

**Comment by ilg-ul** [comment]
> This should fix #103.

does the Travis masOS come with all tools required to build openocd? normally autotools are not part of the macOS distribution, not even part of the developer tools.

**Comment by timsifive** [comment]
> does the Travis masOS come with all tools required to build openocd? normally autotools are not part of the macOS distribution, not even part of the developer tools.

I don't know. The Travis OSX build took so long to start that I never watched one happen. This change adds building with clang, which should get us most of the benefit.

**Review by palmer-dabbelt — APPROVED** [review]
LGTM

**Pull request merged**
