### PR TITLE
fix fespi flash after registers were renamed.

### PR DESCRIPTION
**Pull request by timsifive**
Also made a number of functions static.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
I think @mwachs5 was in the process of testing this.

**Comment by mwachs5** [comment]
Is this the fix you think you need to fix Flashing? Or is this just one piece of it?

**Comment by mwachs5** [comment]
This worked for me to flash HiFive1 with a few demos.

**Review by mwachs5 — APPROVED** [review]
works for me to flash HiFive1

**Comment by timsifive** [comment]
This should be the entire fix to fix HiFive1 flashing.

**Pull request merged**
