### PR TITLE
Clean up this JTAG debug code.

### PR DESCRIPTION
**Pull request by timsifive**

### CODE REVIEW

**Comment by timsifive** [comment]
Can I get a review on this?

**Comment by timsifive** [comment]
Can you review this, please?

**Comment by mwachs5** [comment]
How do you get the JTAG debug output after this change? Does it still show up with "-d"? I'm not familiar with this other macro

**Comment by mwachs5** [comment]
Also, how does this relate to the Upstream? Does this just make it match the upstream version?

**Comment by timsifive** [comment]
To get these log messages, configure OpenOCD with `--enable-verbose-jtag-io`, and run with `-d`. These macros are currently used to debug JTAG drivers, and are disabled by default to preserve performance.

This change gets us closer to upstream, but upstream does not have equivalent debug statements at all.

**Comment by mwachs5** [comment]
Presumably the riscv-tests/debug tests still pass when you do the above debug steps? (since it is replacing code which was basically commented out with something that is actually usable)?

**Comment by timsifive** [comment]
Sample output:
```
Debug: 7876 755 core.c:847 default_interface_jtag_execute_queue(): JTAG IR SCAN to RUN/IDLE
Debug: 7877 755 core.c:852 default_interface_jtag_execute_queue():   5b out: 11
Debug: 7878 755 core.c:847 default_interface_jtag_execute_queue(): JTAG DR SCAN to RUN/IDLE
Debug: 7879 755 core.c:852 default_interface_jtag_execute_queue():   40b out: 5800000001
Debug: 7880 755 core.c:857 default_interface_jtag_execute_queue():   40b  in: 5800000000
```

**Comment by mwachs5** [comment]
thx

**Review by mwachs5 — APPROVED** [review]

**Comment by timsifive** [comment]
All tests still pass.

**Pull request merged**
