### PR TITLE
Merge up to a3ed12401 from upstream.

### PR DESCRIPTION
**Pull request by timsifive**
Merge commit 'a3ed12401b1f7d9578fb7da881d3504e07acfc27' into from_upstream
    
Conflicts:
src/target/riscv/riscv-013.c
src/target/riscv/riscv.c

### CODE REVIEW

**Comment by JanMatCodasip** [comment]
I will be able to review this PR during this week.

**Comment by timsifive** [comment]
@JanMatCodasip Are you able to review this? I'd like to speed up at least the merge-down process.

**Comment by MarekVCodasip** [comment]
@JanMatCodasip asked me to take a look at it. From our side, it looks fine.

**Review by MarekVCodasip — APPROVED** [review]

**Comment by EccoTheDolphin** [comment]
@JanMatCodasip  , @timsifive  this removes `set_prefer_sba` . Is it intentional?

**Comment by TommyMurphyTM1234** [comment]
> @JanMatCodasip , @timsifive this removes set_prefer_sba . Is it intentional?

FWIW it was previously marked as deprecated and deprecated features are usually removed after a judicious period of time:

* https://github.com/riscv/riscv-openocd/pull/508

**Comment by EccoTheDolphin** [comment]
> > @JanMatCodasip , @timsifive this removes set_prefer_sba . Is it intentional?
> 
> FWIW it was previously marked as deprecated and deprecated features are usually removed after a judicious period of time:
> 
> * [Selection of memory access methods, aampostincrement detection #508](https://github.com/riscv/riscv-openocd/pull/508)

Ah.. I see . Missed that. Thanks for clarifying

**Comment by timsifive** [comment]
Specifically, `set_prefer_sba` has been marked deprecated since September of 2020.

**Pull request merged**
