### PR TITLE
flash/nor/spi: add micron MT25QU01G

### PR DESCRIPTION
**Pull request by jaehoon-sifive**
1Gbit SPI flash on VCU118 Rev. 2.0

### CODE REVIEW

**Comment by jaehoon-sifive** [comment]
> 1Gbit SPI flash on VCU118 Rev. 2.0

It's been tested and verified on VCU118 Rev 2.0

**Review by timsifive — APPROVED** [review]
Thank you!

**Comment by DecodeTheEncoded** [comment]
@jaehoon-sifive Hello, I wonder how to apply this? Does this mean something like `flash bank spi0 fespi 0x20000000 0 0 0 $_TARGETNAME_0 0x10014000` will work automatically? Thanks

**Comment by jaehoon-sifive** [comment]
> @jaehoon-sifive Hello, I wonder how to apply this? Does this mean something like `flash bank spi0 fespi 0x20000000 0 0 0 $_TARGETNAME_0 0x10014000` will work automatically? Thanks

Hi, @jerryhethatday 
Yes, it will work automatically if you are using this flash on your board(MT25QU01G)

**Pull request merged**
