### PR TITLE
From upstream

### PR DESCRIPTION
**Pull request by timsifive**

### CODE REVIEW

**Comment by timsifive** [comment]
Can I get a review for this?

**Comment by ilg-ul** [comment]
I don't know how you got the commits on the from_upstream branch, but when trying to use it, I noticed many differences compared to the OpenOCD master.

I would suggest a full merge with the OpenOCD master, to be sure you do not miss anything.

**Comment by timsifive** [comment]
I used `git merge master`. This should bring in all changes that were in the openocd master when I ran the command. Can you point to specific changes that are missing?

**Comment by ilg-ul** [comment]
Then I probably did something wrong.

What puzzles me is that the commit IDs differ, for example:

- https://github.com/riscv/riscv-openocd/commit/6020301640e9c77c283675fc42d967185c940521
- http://repo.or.cz/openocd.git/commit/aba11ae6e2b63129512473906816d2051becf285

If I compare the OpenOCD `master` with your `from_upstream`, I get:

- https://github.com/gnu-mcu-eclipse/openocd/compare/master...from_upstream

I expected only a few files to be affected by your changes, not 106, as reported.

Again, maybe I did something wrong in my repository, since tracking both OpenOCD master and the RISC-V branches was a real challenge, but it might also be something wrong in your branches.

I suggest you also do a compare between your `from_upstream` and the OpenOCD master, and see the result.

**Comment by mwachs5** [comment]
Will this resolve any of the open issues (e.g. #202 )

**Comment by mwachs5** [comment]
@timsifive do you mean `git merge upstream/master`?

**Comment by timsifive** [comment]
This is a prerequisite to solving #202.

I actually run `git merge master`, but before that I do a `git pull` in that branch which pulls changes from upstream.

**Comment by ilg-ul** [comment]
Tim, please note that the `master` branch present in your repo is far from being up to date with the OpenOCD master, the last commit I see is from June 2017.

**Comment by timsifive** [comment]
What's the git remote where you're seeing that change? I have:
```
openocd	https://git.code.sf.net/p/openocd/code (fetch)
openocd	https://git.code.sf.net/p/openocd/code (push)
```

**Comment by ilg-ul** [comment]
for the old commit, see https://github.com/riscv/riscv-openocd/tree/master

in my repo I use git://git.code.sf.net/p/openocd/code

**Comment by ilg-ul** [comment]
Could you update your `master` branch to the latest OpenOCD commit, push it, and then use the GitHub compare feature (you need to manually add `/compare` to the URL and you'll get the compare page).

Then compare the up-to-date `master` with your `from_upstream`.

**Comment by ilg-ul** [comment]
> update your master branch to the latest OpenOCD commit

perhaps a safer option would be to checkout the latest original OpenOCD commit as a new branch, maybe there is something wrong with your current `master` branch.

**Comment by timsifive** [comment]
So we're using the same OpenOCD repo.

What is the June commit that you're seeing in OpenOCD  master that I am not?

**Comment by ilg-ul** [comment]
> What is the June commit that you're seeing in OpenOCD master that I am not?

https://github.com/riscv/riscv-openocd/tree/master

**Comment by timsifive** [comment]
https://github.com/riscv/riscv-openocd/tree/master is not the OpenOCD master. That's the RISCV tree.

In another thread you mentioned that you used the RISCV `from_upstream` branch (which is the one this PR is for) as the "riscv mainline." You should have used the `riscv` branch instead, but I don't think you missed out on much so I didn't make a big deal out of it.

When I merge master, that has nothing to do with `master` in riscv-openocd.

**Comment by timsifive** [comment]
(The June commit in that link is from 2017.)

**Comment by ilg-ul** [comment]
I don't know what it is so difficult to understand.

I forked your repo as https://github.com/ilg-ul/riscv-openocd, added the OpenOCD remote, checked in master, pushed everything to GitHub and used it to compare with your `from_upstream`:

https://github.com/ilg-ul/riscv-openocd/compare/from_upstream...oocd-master

If you think it is ok to have 83 files changed, no problem.

**Comment by timsifive** [comment]
I don't understand why you're getting some output, but eg. the first file listed in that diff (HACKING) is identical between OpenOCD `master` and riscv `from_upstream`.

That aside, you can't usefully compare branches since we don't care about changes added to OpenOCD `master` after we last merged from there. Generally to see what's changed in our branch I use: ``git diff `git merge-base master riscv` riscv``

**Review by mwachs5 — APPROVED** [review]
rubber stamp based on testing as much HW / Emulators as possible

**Pull request merged**
