### PR TITLE
Doxygen style, too.

### PR DESCRIPTION
**Pull request by timsifive**
Change-Id: I85e60e8577c4177ac7094ae41ee84357b292a89c

### CODE REVIEW

**Review by GregSavin — APPROVED** [review]
Do Doxygen style issues get flagged by the checkpatch script?

**Comment by timsifive** [comment]
No. @aka-sps brought them up.

**Comment by aka-sps** [comment]
There are a lot of invalid Doxygen tags in the openocd srs (most of them are out of 'riscv' target).
In 'riscv' there are, for example, `@size` instead `@par size`.

Doxygen itself is the best checker.

**Comment by aka-sps** [comment]
Probably we should not bother about the style because the document doc/manual/style.txt itself violates official standards.
For example, typedef naming: http://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

**Comment by timsifive** [comment]
We have to conform to the OpenOCD style as enforced by the script, otherwise our work will not be accepted upstream. OpenOCD is not a GNU project.

As for Doxygen, I'm happy to make our code clean with it, but I don't want to clean up code that we didn't write for RISC-V support. OpenOCD has its own system for accepting contributions to fix that.

**Comment by aka-sps** [comment]
ANSI/ISO standards reserve '_t'-ended identifiers too.
There were commits with their own definitions of time_t.

**Pull request merged**
