### PR TITLE
From upstream

### PR DESCRIPTION
**Pull request by timsifive**
Merge commit '9f23a1d7c1e27c556ef9787b9d3f263f5c1ecf24' into from_upstream

### CODE REVIEW

**Comment by timsifive** [comment]
Lots of changes (a lot of "int timeout" -> "unsigned int timeout"), but very few that might affect RISC-V.

**Comment by JanMatCodasip** [comment]
I have started checking the changes and would like to finish by the end of the week.

**Review by JanMatCodasip — APPROVED** [review]
I have finished checking the changes (visually) and it looks all right to me.

**Comment by timsifive** [comment]
Thanks for continuing to review these. We're slowly catching up...

**Pull request merged**
