### PR TITLE
Set SIZE for watchpoint of type2 trigger

### PR DESCRIPTION
**Pull request by wxjstz**
Instruction fetch take place at fixed addresses, so ANY can be used to
set SIZE. But for a watchpoint, the exact SIZE needs to be set. For
example, to set a watchpoint for a structure, the address of accessing
the structure object in the code is not always the starting address of
the structure.

Change-Id: I8b514ca1ba097a5fe481d132a342f07641bee598
Signed-off-by: Xiang W <wxjstz@126.com>

### CODE REVIEW

**Comment by JanMatCodasip** [comment]
> But for a watchpoint, the exact SIZE needs to be set. For
example, to set a watchpoint for a structure, the address of accessing
the structure object in the code is not always the starting address of
the structure.

I am afraid the purpose of of `mcontrol.size` field has been misunderstood here.

`Mcontrol.size` is says which sizes of load/store access (e.g. 1-byte store, half-word store, word store ...) are going to trigger the watchpoint. It is not used to cover a range of addresses (for example whole C structure).

To set up a watchpoint on a certain range of addresses, `mcontrol.match` field shall be used. It may be even be needed to chain two triggers (`mcontrol.chain`) to accomplish the goal - depending on what the address range looks like. 

Note that not all hardware will support this advanced (and optional) trigger functionality - trigger chaining & advanced mcontrol.match options may not be available.

**Review by JanMatCodasip — CHANGES_REQUESTED** [review]
The main issue here is that `mcontrol.size` cannot be used to go set up watchpoint on a range of addresses (see my previous comment for explanation).

**Comment by wxjstz** [comment]
> > But for a watchpoint, the exact SIZE needs to be set. For
> > example, to set a watchpoint for a structure, the address of accessing
> > the structure object in the code is not always the starting address of
> > the structure.
> 
> I am afraid the purpose of of `mcontrol.size` field has been misunderstood here.
> 
> `Mcontrol.size` is says which sizes of load/store access (e.g. 1-byte store, half-word store, word store ...) are going to trigger the watchpoint. It is not used to cover a range of addresses (for example whole C structure).
> 
> To set up a watchpoint on a certain range of addresses, `mcontrol.match` field shall be used. It may be even be needed to chain two triggers (`mcontrol.chain`) to accomplish the goal - depending on what the address range looks like.
> 
> Note that not all hardware will support this advanced (and optional) trigger functionality - trigger chaining & advanced mcontrol.match options may not be available.

You mean need to set the watchpoint for each object of the base data type of the structure.
```c
struct point {
  uint32_t x;
  uint32_t y;
} pp; 
```
Such a structure requires two triggers?

This is unreasonable, if I set a 32-bit watchpoint to the variable a
((char*) &a)[1] = 11
Such code should be catchable by trigger.
So setting a 64bit watchpint for pp can catch the changes of pp.x and pp.y

**Comment by timsifive** [comment]
For mcontrol (type 2) triggers, size refers to the *access size*. Not an address range. In the example of the struct given above, your options are:
2 chained triggers, one using ge (2) match, and the other using lt (3) match.
A single trigger using napot (1) match. This can work if the struct has a size that is a power of 2 of number of bytes, and the actual address has the same alignment.

**Comment by wxjstz** [comment]
> For mcontrol (type 2) triggers, size refers to the _access size_. Not an address range. In the example of the struct given above, your options are: 2 chained triggers, one using ge (2) match, and the other using lt (3) match. A single trigger using napot (1) match. This can work if the struct has a size that is a power of 2 of number of bytes, and the actual address has the same alignment.

thk. RISC-V trigger can't catch the following data changes.
```c
uint32_t a = 0;
((char *) &a)[1] = 1; /* can't catch*/
```
This is a spec bug?

**Comment by JanMatCodasip** [comment]
This is not a spec bug. RISC-V triggers are able to catch the changes from your example - if you use the approach suggested by Tim and me above.

**Comment by wxjstz** [comment]
> This is not a spec bug. RISC-V triggers are able to catch the changes from your example - if you use the approach suggested by Tim and me above.

Use two chained triggers, one use ge match, and other use lt match?
This consumes too many triggers.

**Comment by wxjstz** [comment]
> > This is not a spec bug. RISC-V triggers are able to catch the changes from your example - if you use the approach suggested by Tim and me above.
> 
> Use two chained triggers, one use ge match, and other use lt match? This consumes too many triggers.

match(1) may be best. thk @JanMatCodasip @timsifive

**Comment by wxjstz** [comment]
please review #725 @JanMatCodasip @timsifive

**Pull request closed without merging**
