### PR TITLE
From upstream

### PR DESCRIPTION
**Pull request by timsifive**
This is obviously a huge change, but it's simply the result of merging upstream into our branch. They're pretty busy. I've checked riscv-tests/debug `make all`, HiFive1 board, and Arty with E21.

### CODE REVIEW

**Comment by GregSavin** [comment]
OK so the 581b9 commit reflects the only conflict resolutions that were required (not many).  Sounds like no regressions on the tests either.

**Review by GregSavin — APPROVED** [review]

**Review by cgsfv — APPROVED** [review]
Looks like a fairly low-risk merge.

**Comment by timsifive** [comment]
There were conflicts in the following:
	doc/openocd.texi
	src/flash/nor/at91sam4.c
	src/flash/nor/nrf5.c
	src/jtag/drivers/cmsis_dap_usb.c
	src/rtos/Makefile.am
	src/rtos/nuttx.c
	src/rtos/rtos.c
	src/target/arm_adi_v5.c
	src/target/cortex_a.c
	src/target/riscv/batch.c
	src/target/riscv/opcodes.h
	src/target/riscv/program.h
	src/target/riscv/riscv-011.c
	src/target/riscv/riscv-013.c
	src/target/riscv/riscv.c
	src/target/riscv/riscv.h
	src/target/target.c
	tcl/target/stm32f7x.cfg

The riscv ones were mainly because git was choosing a pretty old common ancestor. The RTOS ones were because we added the riscv "rtos" to various lists. I looked at the overall diff afterwards and it seems reasonable.

**Comment by aka-sps** [comment]
If you are not using an explicit merge, please specify the SHA-1 of "upstream" commit you used at least in the comment.

**Comment by GregSavin** [comment]
In general, is 'merge' is preferred over 'squash and merge' whenever merging from upstream?

**Comment by timsifive** [comment]
Oh, is git's common ancestor finding messed up (it always finds a really old one, which makes merges more painful than they ought to be) because I'm using squashed commits? That sounds plausible. I'll try to remember to not squash the commits in the future.

**Comment by aka-sps** [comment]
Yesterday's "upstream" is not today's "upstream". After reverse engineering of your commit you can see that you consider "upstream" SHA-1: ea41048830f3ef79129fdbf3623d708585929f5b but chronologically, there were three additional commits before your commit (3da1b2, 5b350 and e406f2). You did not mention what commit was "upstream" for you. You didn’t mention the source repository where was "upstream" for you. Information about the authorship and contribution was lost too.

There is a simple model of release / development. 
You can have two branches: for development (all details) and for releases(squashed commits).
You can 'squash and merge' from development branch into the release branch but you need to merge back from release branch to the development branch to mark which commits from development branch are already in release branch.
You can distribute a clean release branch, but you can always find development details.

Of course, before the merging of "upstream" master branch, you need to synchronize your master branch with the master branch of "upstream" repository.

Thank you for understanding.

**Pull request merged**
