### PR TITLE
Add cfg for cjtag on Olimex ARM-USB-OCD-H

### PR DESCRIPTION
**Pull request by timsifive**
Change-Id: I240e33491752eac8d2f683ec3598b17570f2a820
Signed-off-by: Tim Newsome <tim@sifive.com>

### CODE REVIEW

**Comment by sifivekevin** [comment]
Don't know.  I merely copied the Olime ARM-USB-TINY-H cjtag script and change the device ID to match the Olimex ARM-USB-OCD-H probe.  I'm assuming the oscan1 is simply not valid for cjtag.

**Review by GregSavin — APPROVED** [review]
Ah OK, I see, the script name includes cjtag, so from the file name it's clear what this is intended for.   Presumably somebody could copy the script and remove the oscan1 enabling line, and that modification would probably work for regular JTAG in that case, but I think I get it... this script is intended for cJTAG.  Makes sense to me.

**Comment by sifivekevin** [comment]
Yep, but there is already a script for ARM-USB-OCD-H, so no one should need to modify this one.  The script names are a little screwy, but making them consistent has ripple effects across a lot of tooling.  Might be worth doing sometime in the future.

**Comment by TommyMurphyTM1234** [comment]
I'm confused.

The subject/title of this issue is

> Add cfg for cjtag on Olimex ARM-USB-OCD-H

But the script added has this:

https://github.com/riscv/riscv-openocd/commit/c56aa667c2ffee906a6d7a7084b70bece863fc73#diff-87bd0cd0f9662a802467316647a6c0f94390f3fc151564fe5cbaa46b65ecb6d5R7

```
# Olimex ARM-USB-TINY-H
#
# http://www.olimex.com/dev/arm-usb-tiny-h.html
#
```

and then this

https://github.com/riscv/riscv-openocd/commit/c56aa667c2ffee906a6d7a7084b70bece863fc73#diff-87bd0cd0f9662a802467316647a6c0f94390f3fc151564fe5cbaa46b65ecb6d5R14

`ftdi_device_desc` "Olimex OpenOCD JTAG ARM-USB-OCD-H"

[arm-usb-tiny-h](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-TINY-H/) and [arm-usb-ocd-h](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-OCD-H/) are different JTAG interfaces.

If the intention is as per the subject/title then I think that the script comments need to be modified/cleaned up and the script name should logically be 

`ftdi/olimex-arm-usb-ocd-h-cjtag.cfg`

to complement the already existing script:

https://github.com/riscv/riscv-openocd/blob/riscv/tcl/interface/ftdi/olimex-arm-usb-ocd-h.cfg

I don't think that it should be:

`ftdi/olimex-arm-usb-ocd-cjtag.cfg`

i.e. the "-h" part should not be omitted.

Any comments/feedback?

**Comment by sifivekevin** [comment]
Agreed on all points.  My fault for not cleaning up the comments.

**Comment by TommyMurphyTM1234** [comment]
> [arm-usb-tiny-h](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-TINY-H/) and [arm-usb-ocd-h](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-OCD-H/) are different JTAG interfaces.
> 

Just to add to the confusion the configuration file added by https://github.com/riscv/riscv-openocd/commit/c56aa667c2ffee906a6d7a7084b70bece863fc73 is named:

olimex-arm-jtag-cjtag.cfg

and olimex-arm-jtag is yet a third different interface

https://www.olimex.com/Products/ARM/JTAG/ARM-JTAG/

different to olimex-arm-usb-tiny, olimex-arm-usb-tiny-h, olimex-arm-usb-ocd and olimex-arm-usb-ocd-h

https://www.olimex.com/Products/ARM/JTAG/ARM-USB-TINY/
https://www.olimex.com/Products/ARM/JTAG/ARM-USB-TINY-H/
https://www.olimex.com/Products/ARM/JTAG/ARM-USB-OCD/
https://www.olimex.com/Products/ARM/JTAG/ARM-USB-OCD-H/

So I'm not sure which Olimex probe(s?) the new configuration file is expected to support from the naming and the comments in the file...

**Comment by sifivekevin** [comment]
I need to support the ARM-USB-OCD-H and ARM-USB-TINY-H devices (then JTAG and cJTAG variants of each, so four scripts).  I'm not familiar with, nor have, the other Olimex devices (the non-H ones and the arm-jtag device).  

ARM-USB-TINY-H: olimex-arm-usb-tiny-h.cfg, and olimex-arm-usb-tiny-h-cjtag.cfg
ARM-USB-OCD-H: olimex-arm-usb-ocd-h.cfg, and olimex-arm-usb-ocd-h-cjtag.cfg

If we want to go further and address the other devices:

Rename olimex-jtag-tiny.cfg --> olimex-arm-usb-tiny.cfg
Add cJTAG variants for TINY, and OCD: olimex-arm-usb-tiny-cjtag.cf, olimex-arm-usb-ocd-cjtag.cfg

That should make everything consistent.

**Pull request merged**
