### PR TITLE
From upstream - SPDX/copyright changes to file comment headers

### PR DESCRIPTION
**Pull request by TommyMurphyTM1234**
With OpenOCD heading for release v0.12.0 (at the time of writing at rc3: https://sourceforge.net/p/openocd/mailman/message/37752067/) maybe it's an opportune time to try to re-sync the riscv-openocd fork with the upstream repo. This integrates upstream changes into riscv-openocd, resolves any issues between upstream changes and local changes, and provides a base from which to more easily to upstream local changes from riscv-openocd to the upstream project eventually.

To this end, this is a first PR to integrate some of the changes upstream. Specifically, the changes to many files to update the SPDX/copyright header comments. For many of the changed files this is the only change. But for others there are also other (functional/logic) changes. For the latter set of files ONLY the SPDX/copyright header comment changes are integrated with this PR. Functional/code and other (e.g. documentation, ancillary file etc.) changes will be done incrementally in subsequent PR(s).

Just to reiterate, this PR should be innocuous since it does not involve any functional/code changes so the only testing that I have done is to bootstrap/configure/make afresh. 

If there are any issues with this PR or this approach please let me know. Thanks.

### CODE REVIEW

**Comment by TommyMurphyTM1234** [comment]
> Check Code Style (checkpatch) / check (pull_request) Failing after 36s

OK - I guess that I need to also update the `checkpatch` stuff?

Edit: hmmm - this is proving more difficult than I thought. When I pull in the upstream `checkpatch` related changes I get errors when I try to push.
```
user@wagtail:~/Downloads/openocd/riscv-openocd-tommy$ git push
Username for 'https://github.com': tommy_murphy@hotmail.com
Password for 'https://tommy_murphy@hotmail.com@github.com': 
Traceback (most recent call last):
  File "tools/scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
Traceback (most recent call last):
  File "tools/scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
Traceback (most recent call last):
  File "tools/scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
Traceback (most recent call last):
  File "tools/scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
Traceback (most recent call last):
  File "tools/scripts/spdxcheck.py", line 6, in <module>
    from ply import lex, yacc
ModuleNotFoundError: No module named 'ply'
WARNING:BAD_SIGN_OFF: Do not use whitespace before Signed-off-by:
#1051: FILE: tools/scripts/checkpatch.pl:635:
 	Signed-off-by:|

WARNING:BAD_SIGN_OFF: Use a single space after Signed-off-by:
#1051: FILE: tools/scripts/checkpatch.pl:635:
 	Signed-off-by:|

ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#1051: FILE: tools/scripts/checkpatch.pl:635:
 	Signed-off-by:|

WARNING:BAD_SIGN_OFF: Do not use whitespace before Acked-by:
#1053: FILE: tools/scripts/checkpatch.pl:637:
 	Acked-by:|

WARNING:BAD_SIGN_OFF: Use a single space after Acked-by:
#1053: FILE: tools/scripts/checkpatch.pl:637:
 	Acked-by:|

ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#1053: FILE: tools/scripts/checkpatch.pl:637:
 	Acked-by:|

WARNING:BAD_SIGN_OFF: Do not use whitespace before Tested-by:
#1054: FILE: tools/scripts/checkpatch.pl:638:
 	Tested-by:|

WARNING:BAD_SIGN_OFF: Use a single space after Tested-by:
#1054: FILE: tools/scripts/checkpatch.pl:638:
 	Tested-by:|

ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#1054: FILE: tools/scripts/checkpatch.pl:638:
 	Tested-by:|

WARNING:BAD_SIGN_OFF: Do not use whitespace before Reviewed-by:
#1055: FILE: tools/scripts/checkpatch.pl:639:
 	Reviewed-by:|

WARNING:BAD_SIGN_OFF: Use a single space after Reviewed-by:
#1055: FILE: tools/scripts/checkpatch.pl:639:
 	Reviewed-by:|

ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#1055: FILE: tools/scripts/checkpatch.pl:639:
 	Reviewed-by:|

WARNING:BAD_SIGN_OFF: Do not use whitespace before Reported-by:
#1056: FILE: tools/scripts/checkpatch.pl:640:
 	Reported-by:|

WARNING:BAD_SIGN_OFF: Use a single space after Reported-by:
#1056: FILE: tools/scripts/checkpatch.pl:640:
 	Reported-by:|

ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#1056: FILE: tools/scripts/checkpatch.pl:640:
 	Reported-by:|

WARNING:BAD_SIGN_OFF: Do not use whitespace before To:
#1058: FILE: tools/scripts/checkpatch.pl:642:
 	To:|

WARNING:BAD_SIGN_OFF: Use a single space after To:
#1058: FILE: tools/scripts/checkpatch.pl:642:
 	To:|

ERROR:BAD_SIGN_OFF: Unrecognized email address: '|'
#1058: FILE: tools/scripts/checkpatch.pl:642:
 	To:|

WARNING:BAD_SIGN_OFF: Do not use whitespace before Cc:
#1059: FILE: tools/scripts/checkpatch.pl:643:
 	Cc:

WARNING:BAD_SIGN_OFF: Use a single space after Cc:
#1059: FILE: tools/scripts/checkpatch.pl:643:
 	Cc:

ERROR:BAD_SIGN_OFF: Unrecognized email address: ''
#1059: FILE: tools/scripts/checkpatch.pl:643:
 	Cc:

ERROR:NO_AUTHOR_SIGN_OFF: Missing Signed-off-by: line by nominal patch author 'Tommy Murphy <tommy_murphy@hotmail.com>'

total: 8 errors, 14 warnings, 0 checks, 9632 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

"[PATCH] From upstream - patch checking updates required in order to" has style problems, please review.

NOTE: Ignored message types: AVOID_EXTERNS BLOCK_COMMENT_STYLE COMPLEX_MACRO CONST_STRUCT ENOSYS FILE_PATH_CHANGES GERRIT_CHANGE_ID LINE_SPACING LOGICAL_CONTINUATIONS MACRO_WITH_FLOW_CONTROL NEW_TYPEDEFS PARENTHESIS_ALIGNMENT PREFER_DEFINED_ATTRIBUTE_MACRO PREFER_FALLTHROUGH PREFER_KERNEL_TYPES SPLIT_STRING SSCANF_TO_KSTRTO SWITCH_CASE_INDENT_LEVEL TRACING_LOGGING VOLATILE

NOTE: If any of the errors are false positives, please report
      them to the openocd-devel mailing list or prepare a patch
      and send it to Gerrit for review.
```
I see this post:

* https://ypl.coffee/checkpatch-python-2/

which mentions @palmer-dabbelt's patch here:

* https://www.spinics.net/lists/kernel/msg3484955.html

But I don't know if that's what I need here and, in any case, I cannot resolve the patch to the latest `checkpatch.pl` script which seems very much changed from when the patch was created.

Unfortunately, my idea of checking in innocuous/non code changes (to the SPDX/copyright header comments only) doesn't look as simple as I had assumed... :-|

**Comment by timsifive** [comment]
We actually run checkpatch more aggressively than the upstream project does. I don't know how it happens, but occasionally we do take changes from upstream which violate checkpatch. Generally I've fixed the problems here (which is not great because it means we diverge even more from upstream).

More generally, when taking changes from upstream I prefer to simply get all changes, in order, up to a certain point. Cherry-picking just changes that seem innocuous just leads to a more confusing version history. (Occasionally I've cherry picked a single bugfix.)

**Comment by TommyMurphyTM1234** [comment]
> We actually run checkpatch more aggressively than the upstream project does. I don't know how it happens, but occasionally we do take changes from upstream which violate checkpatch. Generally I've fixed the problems here (which is not great because it means we diverge even more from upstream).
> 
> More generally, when taking changes from upstream I prefer to simply get all changes, in order, up to a certain point. Cherry-picking just changes that seem innocuous just leads to a more confusing version history. (Occasionally I've cherry picked a single bugfix.)

Thanks @timsifive.

There are a lot of changes to the upstream `checkpatch` related stuff including changes that allow, say, `// ... SPDX ...` style comments at the top of a C source file which was rejected in the past. (OpenOCD (and GNU style?) contribution rules actually now mandate `// ... SPDX ...` for C/C++ source files and `/* ... SPDX ... */` for header files).

Since my style of cherry picking doesn't sound like the correct approach, I'll take a step back and see if I can tackle it differently. I understand from your comments earlier than you don't have the bandwidth for an upstream re-sync right now so hopefully I can help...

**Comment by timsifive** [comment]
What I'd like to do is to start from the merge base, and then take a chunk of changes from then forward and merge all those here. I started that, but ran into some intermittent regression in EtriggerTest. Since that is a new feature, it's possible that it's not a regression at all and simply a bug, but then I got side tracked and haven't had time to dig into it yet.

**Pull request closed without merging**
